#!/bin/zsh

source platform

service=$1

# Restart all services
if [[ "$service" == "" ]]; then
    ./web/stop
    ./web/start
else
    # Restart a single service
    stop_service $service
    start_service $service
fi
