#!/bin/zsh
#
# Start BOSS apps.
#
# This script is expected to be ran from root of `ays-server`.
#

source platform

echo "Starting web services..."
start_service web/app/io.bithead.boss/app.py
start_service web/app/io.bithead.boss-code/app.py
start_service web/app/io.bithead.json-formatter/app.py
